fix: issue when user switches to different app
HttpException: Software caused connection abort
Arises when the user switches to a different app while the analysis is in progress on Android 13 and above due to battery optimization settings.